---
- hosts: 192.168.0.148
  remote_user: dl
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: "Install MySQL"
      apt: name=mysql-server state=installed

    - name: Start the MySQL service
      action: service name=mysql state=started

